const POSITION_ASSIGNMENT_TYPES = {
    PRIMARY: 'PRIMARY',
    ACTING: 'ACTING',
    DEPUTY: 'DEPUTY',
};

class USER_CONSTANTS {
    static POSITION_ASSIGNMENT_TYPES = POSITION_ASSIGNMENT_TYPES;

    static POSITION_ASSIGNMENT_TYPE_PRIMARY = POSITION_ASSIGNMENT_TYPES.PRIMARY;
    static POSITION_ASSIGNMENT_TYPE_ACTING = POSITION_ASSIGNMENT_TYPES.ACTING;
    static POSITION_ASSIGNMENT_TYPE_DEPUTY = POSITION_ASSIGNMENT_TYPES.DEPUTY;

    static MAX_LOGIN_FAIL_ATTEMTS = 3;
    static USER_LOGIN_BLOCK_DURATION = 3;

    static STATUS_NOT_ACTIVATED = 0;
    static STATUS_ACTIVATED = 0;
    static STATUS_BLOCKED = 90;
    static STATUS_DELETED = 99;

    static OTP_PURPOSES = Object.freeze({
        LOGIN: "LOGIN",
        REGISTER: "REGISTER",
        RESET_PASSWORD: "RESET_PASSWORD",
    });

    static TM_PHONE_REGEX = /^(6[1-5]|71)\d{6}$/;
}

module.exports = USER_CONSTANTS;