const POSITION_ASSIGNMENT_TYPES = {
    PRIMARY: 'PRIMARY',
    ACTING: 'ACTING',
    DEPUTY: 'DEPUTY',
};
const POSITION_ASSIGNMENT_TYPES_ENUM = Object.values(POSITION_ASSIGNMENT_TYPES);

module.exports = { POSITION_ASSIGNMENT_TYPES, POSITION_ASSIGNMENT_TYPES_ENUM }